package com.repele.astronomypictureoftheday.presentation

import androidx.lifecycle.ViewModel
import com.repele.astronomypictureoftheday.data.MediaType
import com.repele.astronomypictureoftheday.data.PictureOfTheDay
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow

class PituresViewModel() : ViewModel() {
    private val _pictures = MutableStateFlow<List<PictureOfTheDay>>(mockElements())
    val pictures = _pictures.asStateFlow()

    private fun mockElements() = listOf(
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),  PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),  PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),  PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
        PictureOfTheDay(
            date = "2021-11-25",
            mediaType = MediaType.IMAGE,
            title = "At the Shadow's Edge",
            explanation = "explanation",
            contentUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-1024.jpg",
            hdImageUrl = "https://apod.nasa.gov/apod/image/2111/Gout_EclipseCollage-small.jpg",
            thumbnailUrl = null,
        ),
    )
}